### ISSUE TITLE
Error when building project with docker

### ISSUE THREAD

**Issue by Vagionas** [cb-cities/sierra-charlie#17]
```error /usr/local/share/.config/yarn/global/node_modules/purescript: Command failed.
Exit code: 1
Command: install-purescript --purs-ver=0.12.0 .
Arguments:
Directory: /usr/local/share/.config/yarn/global/node_modules/purescript
Output:
[ SUCCESS ] Check if a prebuilt 0.12.0 binary is provided for Linux (2s)
[ SUCCESS ] Download the prebuilt PureScript binary (5s)
[ FAILURE ] Verify the prebuilt binary works correctly
Error: Command failed: /usr/local/share/.config/yarn/global/node_modules/purescript/purs.bin --version
/usr/local/share/.config/yarn/global/node_modules/purescript/purs.bin: error while loading shared libraries: libtinfo.so.5: cannot open shared object file: No such file or directory
   at makeError (/usr/local/share/.config/yarn/global/node_modules/execa/index.js:172:9)
   at Promise.all.then.arr (/usr/local/share/.config/yarn/global/node_modules/execa/index.js:277:16)


↓ Fallback: building from source


[ FAILURE ] Check if 'stack' command is available
'stack' command is required for building PureScript from source, but it's not found in your PATH. Make sure you have installed Stack and try again. → https://docs.haskellstack.org/en/stable/install_and_upgrade/#linux
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
The command '/bin/sh -c yarn global add purescript elm@0.16' returned a non-zero code: 1
```

**Comment by kks32** [comment]
In `https://github.com/cb-cities/sierra-charlie/blob/master/Dockerfile` change `fedora:latest` to `fedora:26` and see if that works?
